apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: metrics
#   labels:
#     app: metrics
#     service: metrics
# spec:
#   ports:
#     - port: 9000
#       name: http
#   selector:
#     app: metrics
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9000'
        sidecar.istio.io/inject: "true"
      labels:
        app: metrics
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: metrics
      imagePullSecrets:
        - name: default
      containers:
        - name: metrics
          image: registry/registrynamepace/go-test-app:latest
          imagePullPolicy: Always
          ports:
          - name: metrics
            containerPort: 9000
            protocol: TCP
